# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install poetry
      run: pip install poetry
    - name: install dependency
      run: make install
    - name: Test & publish code coverage
      env:
        CC_TEST_REPORTER_ID: bcab0d641b57b4dabecdfac11d60fe91ea962ecaa54fce7d8af0bcac687f9683
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        poetry run coverage run gendiff/scripts/main.py gendiff/json_file1.json gendiff/json_file2.json
        poetry run coverage report
        ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code 0

# with:
      #  coverageCommand: poetry run coverage run gendiff/scripts/main.py gendiff/json_file1.json gendiff/json_file2.json 
    - name: lint
      run: make lint
   
